version: '3.4'

volumes:
  l2_data:

services:
  l2:
    image: public.ecr.aws/i6b2w2n6/nitro-node:curtis3
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - "${PWD}/nodeConfig.json:/config/nodeConfig.json"
      - l2_data:/home/user/.arbitrum
    entrypoint:
      - "/usr/local/bin/nitro"
      - --conf.file=/config/nodeConfig.json
      - --execution.forwarding-target=wss://rpc.curtis.apechain.com/infra-partner-ws
      - --node.feed.input.url=wss://rpc.curtis.apechain.com/feed
      - --parent-chain.connection.url=https://sepolia-rollup.arbitrum.io/rpc
      - --node.data-availability.rest-aggregator.urls="https://rpc.curtis.apechain.com/rest-aggregator"

